### ISSUE TITLE
Update runtime

### ISSUE THREAD

**Issue by SaadiSave** [flathub/org.synfig.SynfigStudio#21]
I have noticed that the runtime version has not been updated to GNOME 40/41. Are there any incompatibilities that are preventing this update?

**Comment by ice0** [comment]
@SaadiSave 
Does it support GTK3? We're still on GTK3.

**Comment by SaadiSave** [comment]
I'll attempt to build it and check

**Comment by SaadiSave** [comment]
Update: It works with both gnome 40 & 41 runtimes. Should I put in a pull request?

**Comment by SaadiSave** [comment]
#22

**Comment by ice0** [comment]
Fixed in this commit: https://github.com/flathub/org.synfig.SynfigStudio/commit/b33c51820023ad4ddc812742552ddd1d2ff718d2
