### ISSUE TITLE
Panel, tool box, etc can not be sizing

### ISSUE THREAD

**Issue by Lvaskz** [flathub/org.synfig.SynfigStudio#3]
Tool box, panel, etc can not be sized in synfig
Cinnamon
64 bit
Linux mint 19

**Comment by Lvaskz** [comment]
I will close this because I was wrong, but I can not see the Icon when I resizing   some panel

**Comment by morevnaproject** [comment]
The solution for this is to add a wrapper script for "synfigstudio" binary, which sets XDG_DATA_DIRS, XCURSOR_PATH and XCURSOR_THEME environment variables. 

I am not sure how to do that for Flatpack, but here's how it is done for NIX - https://github.com/synfig/synfig/blob/master/autobuild/default.nix#L59

**Comment by Lvaskz** [comment]
Are you supporting flatpak version?

**Comment by eszlari** [comment]
Maybe someone could make video, I can't see what's wrong.

**Comment by Lvaskz** [comment]
Hi, now is working properly. I don't know if some one could fix something but the fact is noww is working fine, see
[synfig studio now works fine.flv.tar.gz](https://github.com/flathub/org.synfig.SynfigStudio/files/2718982/synfig.studio.now.works.fine.flv.tar.gz)
