### ISSUE TITLE
Imported sound not playing

### ISSUE THREAD

**Issue by Keyikedalube** [flathub/org.synfig.SynfigStudio#5]
Downloaded the app and started working right away with the tutorials. Later, I found out the app is not playing imported sound.

Steps to reproduce:
1. Launch Synfig
2. Set up face animation (tutorial from Synfig's official website)
3. Import sound file and press play button

OS: Fedora 30 Workstation
DE: GNOME

**Comment by morevnaproject** [comment]
Hi! Can you please check if this works for you in the latest AppImage - https://github.com/synfig/synfig/releases/tag/v1.3.11 (with the same audio file)?

**Comment by Keyikedalube** [comment]
The sound works on the latest AppImage!! Yay!

But I'm facing this same Windows dude issue https://github.com/synfig/synfig/issues/424#issue-256455447

**Comment by morevnaproject** [comment]
Okay, so Flatpack's version has some problems with MLT component.

**Comment by eszlari** [comment]
Does it work if you start the app with
```
flatpak run --socket=pulseaudio org.synfig.SynfigStudio
```
?

**Comment by ice0** [comment]
@eszlari Yes! This helps and sound is playing!
Can you add this parameter to args?
